### PR TITLE
Support GitHub Enterprise

### PR DESCRIPTION
**Pull request by manosim**
### Info
Thanks to @deibeljc for his amazing work on this one!

<table>
  <tr>
    <th>Login</th>
    <th>Enterprise Login</th>
    <th>Dashboard</th>
  </tr>
  <tr>
    <td>
      
    </td>
    <td>
       
    </td>
    <td>
      
    </td>
  </tr>
</table>

### To Do

- [x] Always allow one main github.com account
- [x] Validate Hostname, Client Id, Client Secret
- [x] Alert if Enterprise authWindow url does not exist
- [x] Support multiple GitHub enterprise accounts
- [x] Getting old tests to run
- [x] Open correct url on click (& native notification)
- [x] Fix Mark Notification as Read
- [x] Fix Mark Repo Notifications as Read
- [x] checkHasStarred only for github.com
- [x] Fetch notifications after logging in
- [x] Fix & write new tests
- [x] Fix "all-read" etc. in `routes/notifications`.
- [x] Review Dock Badge functionality
- [x] General cleanup
- [x] Styling (Sidebar & Login with Enterprise)
- [x] Core Review

### Help Wanted

Since I do not have access to a GitHub enterprise account, it would be great if someone can give me access just to a dummy repository. Feel free to DM me on [twitter](https://twitter.com/manosim_).

### CODE REVIEW

**Comment by necramirez** [comment]
I don't see this issue in the To Do list above:
- Clicking on a notification opens the wrong URL in the browser
  - I get:  https://github.mydomain.com/api/v3/repos/my-org/my-repo/pull/4
  - I expect:  https://github.mydomain.com/my-org/my-repo/pull/4

**Comment by manosim** [comment]
@necramirez This should have been fixed now 😄 

Ps. While this is still work in progress (it has reached a usable state) - it would be great if you can test it!

**Comment by necramirez** [comment]
Yup! I can vouch that it's usable! Been using this branch instead of the stable release for around 2 weeks now. 😁 Will update my build now, to check out recent updates. 😄

**Comment by necramirez** [comment]
Repo URL bug is indeed fixed! Marking notifications and repos as read also works for me.

**Comment by necramirez** [comment]
One thing I noticed after I updated, the menu bar icon only turns green sometimes. I tried to click on the refresh button, but it doesn't update the icon color.

Screenshot of icon NOT being green, despite having unread notifications:
image

**Comment by manosim** [comment]
screen shot 2017-05-28 at 22 59 28

screen shot 2017-05-28 at 23 00 34

screen shot 2017-05-28 at 23 02 54

**Pull request merged**
