### PR TITLE
feat: enable unsubscribing notifications

### PR DESCRIPTION
**Pull request by codebytere**
Closes https://github.com/manosim/gitify/issues/402.

When the new unsubscribe icon is clicked, all future notifications for a conversation are muted until one comments on the thread or gets an @mention.

Screen Shot 2020-05-04 at 4 32 02 PM

cc @manosim

### CODE REVIEW

**Comment by JakeSidSmith** [comment]
Can I suggest that we use the same icon as GitHub? 😉 
https://primer.style/octicons/mute

**Comment by manosim** [comment]
I feel like it shouldn't be next to "✔" as it's not a primary action so what I did was to place it on the same line with the "reason" and "date" and it's visible only when you hover over a notification. This way we have more space more icons in the future (if needed). Thoughts on the gif? cc @codebytere @JakeSidSmith 

vJnAul77c4

**Comment by JakeSidSmith** [comment]
I wouldn't have it hidden until hover, especially as it will also mark the notification as complete. I imagine people would be likely to couck it without meaning to and then struggle to find it again.

**Comment by codebytere** [comment]
I'd agree with @JakeSidSmith - definitely better to make it a secondary action but perhaps keep it visible by default 🤔 

would something like this be fine, or would you prefer it right-aligned?

Screen Shot 2020-05-03 at 5 10 36 PM

**Comment by manosim** [comment]
Maybe right aligned and always visible would be perfect if you agree? I think we will have to remove it from the list as well - like we do when pressing on the "check"?

**Comment by codebytere** [comment]
@manosim i _believe_ this should be good to go now! Let me know if there are any other tests you'd like me to add, but i covered the basics based on what i saw was already there.

**Comment by manosim** [comment]
Amazing - thank you for sorting this out @codebytere ! 🎉 
Will give it a couple of days and will cut a new release if nothing else comes up.

**Comment by manosim** [comment]
@codebytere Can you try pushing an empty commit? It looks like GitHub Actions didn't pick up this PR 😢

**Pull request merged**
