### PR TITLE
Support Windows & Linux

### LINKED ISSUE #32: Any plans for linux (ubuntu) support?

### PR DESCRIPTION
**Pull request by manosim**
Closes #32 and #111.
### Cross Testing:
- [ ] OSX
- [ ] Windows 10 (all taskbar positions: bottom, top, left and right)
- [ ] Linux Mint XFCE (top and bottom)
- [ ] Linux Manjaro XFCE (bottom, top, left and right)
- [ ] Ubuntu 14LTS (requires `libappindicator1`, but works)
### Windows Release:
- [ ] Check Autoupdate (.zip or .exe?)
- [ ] Check Autostart
- [x] App Icon (.ico)
### Linux Release:
- [ ] Remove autoupdate button from settings
- [ ] Check Autostart
- [ ] App Icon (?)
### Help Wanted

The app should work fine now on OSX, Windows and some Linux distributions. It would be great if any folks can help with testing. Basically just running the app to see what works and what's broken in different platforms. We do have a private channel in the atom slack team (http://atom-slack.herokuapp.com/) so if you are interested in testing, ping me on Slack in the atom team (username: ekonstantinidis).

### CODE REVIEW

**Comment by mrmlnc** [comment]
Autolaunch works with Windows.

**Comment by TheInitializer** [comment]
GNOME pls? <3

**Comment by Serkan-devel** [comment]
Will there be lxde or lxqt support for this?

**Comment by brpaz** [comment]
Whats the status of this PR?
I can help with Linux version if needed.

**Comment by Serkan-devel** [comment]
Any updates on this?
I'd recommend Appimage as package

**Comment by edubxb** [comment]
Linux support would be awesome! thanks for the effort!

**Comment by probonopd** [comment]
Please ping me once the AppImage is available so that I can include it on appimage.github.io/apps/.

**Comment by jimmed** [comment]
What is the status of this issue? I just built the latest from the `cross-gitify` branch on Ubuntu 18.04, and I'm getting arbitrary JS errors when booting:

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property '0' of null
    at Object.<anonymous> (/home/jim/dev/bucket/gitify/Gitify-linux-x64/resources/app.asar/main.js:22:43)
    at Object.<anonymous> (/home/jim/dev/bucket/gitify/Gitify-linux-x64/resources/app.asar/main.js:215:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (/home/jim/dev/bucket/gitify/Gitify-linux-x64/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/home/jim/dev/bucket/gitify/Gitify-linux-x64/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:571:32)
```

Unsure if this is me having missed some critical build step, or this is the result of incompatibility.

**Comment by manosim** [comment]
It's been a really long time since this PR was opened but I've finally got some time to sort this out in v3. Unless any bugs pop up, the next version will have support for both Windows & Linux. 🎉

**Comment by OskarKlintrot** [comment]
On https://www.gitify.io/ I can see that there is a download-button for Windows but nothing happens when I try to click on it. Is it supposed to be working yet? :)

**Comment by manosim** [comment]
Planning to release support for both Windows & Linux this week (this button was on a hurry to go live on the website 😂)

In the meantime - you can download a pre-release from [this link](https://github.com/manosim/gitify/releases/download/untagged-38c017e947279ffeedeb/Gitify-Setup-3.0.3.exe).

**Comment by JakeSidSmith** [comment]
I cannot access [this link](https://github.com/manosim/gitify/releases/download/untagged-38c017e947279ffeedeb/Gitify-Setup-3.0.3.exe)...

**Comment by manosim** [comment]
Any chance that GitHub allows you to download the artifacts from GitHub Actions? I've made it so that it builds the app for every commit and stores the app as an artifact.
https://github.com/manosim/gitify/actions/runs/71310056

**Comment by JakeSidSmith** [comment]
Oooh, looks like it. I'll hopefully give that a go tomorrow. 👍

**Comment by probonopd** [comment]
There is no AppImage?

**Pull request closed without merging**
