### PR TITLE
Add Github enterprise support

### PR DESCRIPTION
**Pull request by deibeljc**
This is my first pass at adding a functioning enterprise support by adding these two screens

<table>
  <tr>
    <th>New Login Page</th>
    <th>Enterprise Login Page</th>
  </tr>
  <tr>
    <td>
      
    </td>
    <td>
       
    </td>
  </tr>
</table>

This PR still needs the following:
- [ ] General Code Review stuff
- [x] Getting old tests to run
- [ ] New tests
- [ ] General cleanup

### CODE REVIEW

**Comment by manosim** [comment]
Hello @deibeljc! That looks amazing - pretty much what I was thinking about! The main issue is that there is a branch (`v2`) which changes the layout (prepares the surface for enterprise support), so that there is space for enterprise accounts in the sidebar. Can you branch of this one since it will soon get merged into master (or you can wait until it gets merged)? Once I merge v2, I will be more than happy to help you with it! Amazing work, thank you 🎉

**Comment by deibeljc** [comment]
@manosim Oh yeah! I for sure will work on that tonight! Is it a huge change or can I just rebase my branch off of v2?

**Comment by deibeljc** [comment]
@manosim this guy is now rebased off of v2. I need to do some work to make it fully work with V2 so I'll be doing that later tonight!

**Comment by deibeljc** [comment]
It is now fully rebased off of V2 and fully works! 🎉. I just need to update the tests and we can start working on stuff. 

One thing I wanna do (maybe in a separate PR) is support both enterprise and github.com at the same time with tabs on the sidebar sorta like how discord or slack handles multi-groups. What are you thoughts on that?

**Comment by deibeljc** [comment]
All tests are passing now 🎊. Just need to write a couple new tests I think and clean up the enterprise login page as it looks kinda bad right now!

**Comment by manosim** [comment]
@deibeljc That looks amazing! Sorry for not being so responsive - Planning to merge everything over the weekend and finally release `2.0.0` - I can definitely help you either with tests, design or anything else that's left!

**Comment by deibeljc** [comment]
@manosim I think the only thing really left is to fix up the styles for the enterprise login page. If you wanna fix it up real fast so it can be merged this weekend go for it! I am stuck working on other stuff for the very short term so I can't get to it this weekend :(

**Comment by manosim** [comment]
Hey @deibeljc! I'm finally on holidays so I will have some free time to release this! Will make sure everything is up to date (only thing left is update react-router) and then I'll jump onto this one!

**Comment by manosim** [comment]
Hello @deibeljc! I've moved this PR to #279 so I can start doing some styling and more. Is there any chance you can DM me on [twitter](https://twitter.com/manosim_) just to catchup?

**Pull request closed without merging**
